"""
convert_cookies.py
──────────────────
Converts a browser-exported JSON cookies file to Netscape cookies.txt
format that yt-dlp can read.

Usage: python convert_cookies.py <input.json> [output.txt]
"""

import json
import sys
import math
from pathlib import Path


def json_to_netscape(json_path: str, output_path: str) -> None:
    with open(json_path, "r", encoding="utf-8") as f:
        cookies = json.load(f)

    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by convert_cookies.py",
        "",
    ]

    for c in cookies:
        domain = c.get("domain", "")
        # Netscape format: if domain starts with dot, include_subdomains = TRUE
        include_subdomains = "TRUE" if domain.startswith(".") else "FALSE"
        path = c.get("path", "/")
        secure = "TRUE" if c.get("secure", False) else "FALSE"
        # Session cookies have no expiry — use 0
        expiry = c.get("expirationDate", 0)
        expiry_int = int(math.floor(expiry)) if expiry else 0
        name = c.get("name", "")
        value = c.get("value", "")

        lines.append(
            f"{domain}\t{include_subdomains}\t{path}\t{secure}\t{expiry_int}\t{name}\t{value}"
        )

    with open(output_path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")

    print(f"[OK] Converted {len(cookies)} cookies -> {output_path}")


if __name__ == "__main__":
    inp = sys.argv[1] if len(sys.argv) > 1 else "www.instagram.com_json_1790945855948.json"
    out = sys.argv[2] if len(sys.argv) > 2 else "cookies.txt"
    json_to_netscape(inp, out)
